ServerRoot "/usr/local/apache2"
Listen 80

LoadModule mpm_event_module     modules/mod_mpm_event.so
LoadModule authz_core_module    modules/mod_authz_core.so
LoadModule log_config_module    modules/mod_log_config.so
LoadModule headers_module       modules/mod_headers.so
LoadModule proxy_module         modules/mod_proxy.so
LoadModule proxy_http_module    modules/mod_proxy_http.so
LoadModule unixd_module         modules/mod_unixd.so
LoadModule dir_module           modules/mod_dir.so
LoadModule mime_module          modules/mod_mime.so

ServerName   localhost
ServerTokens Prod
ServerSignature Off

TypesConfig conf/mime.types
AddType application/javascript .js
AddType text/css               .css

ErrorLog  /proc/self/fd/2
CustomLog /proc/self/fd/1 combined

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /usr/local/apache2/htdocs

    <Directory "/usr/local/apache2/htdocs">
        Options    -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
        FallbackResource /index.html
    </Directory>

    DirectoryIndex index.html

    # Reverse proxy → Spring Boot (red Docker interna)
    ProxyRequests     Off
    ProxyPreserveHost On

    <Location /api>
        ProxyPass        http://app-service:8080/api
        ProxyPassReverse http://app-service:8080/api
        RequestHeader unset Origin
    </Location>
</VirtualHost>
